import React,{useState}from"react";
import{createRoot}from"react-dom/client";

const I={hero:"/assets/ff-drop.svg",card1:"/assets/ff-drop.svg",card2:"/assets/ff-chroma.svg",card3:"/assets/ff-anniversary.svg"};

function Header(){return <header><div className="brand">DUSK <span>FF MAX</span></div><span>OPÇÕES</span></header>}
function Hero({start}){return <section className="hero"><div><span className="eyebrow">DUSK FF MAX</span><h1>Acesse oportunidades<br/><em>e conteúdos exclusivos.</em></h1><p>Uma experiência gamer premium, criada para apresentar oportunidades e conteúdos de forma clara e organizada.</p><button className="primary" onClick={start}>ATIVAR ACESSO <b>→</b></button></div><div className="heroArt"><img src={I.hero} alt="Arte gamer"/></div></section>}
function Activity(){return <section className="panel activity"><div><span className="eyebrow">ATIVIDADE RECENTE</span><h2>Movimentação da plataforma</h2><p>Novos acessos registrados recentemente.</p></div><div className="activityList">{["acesso registrado","visualizou uma oportunidade","abriu o conteúdo"].map((x,i)=><div key={x}><i>D{i+1}</i><span>Usuário ocultado <small>{x}</small></span><time>{i?"há "+(i*4+4)+" min":"agora"}</time></div>)}</div></section>}
function Card({img,id,onSelect}){return <article className="accountCard"><img src={img} alt="Prévia da oportunidade"/><div className="cardBody"><span className="status">● DISPONÍVEL</span><h3>{id}</h3><p>Conteúdo visual demonstrativo · dados configuráveis.</p><button onClick={onSelect}>ATIVAR ACESSO</button></div></article>}
function Accounts({start}){return <section className="accounts"><div className="sectionTitle"><span className="eyebrow">OPORTUNIDADES</span><h2>OPÇÕES DISPONÍVEIS</h2><p>Estrutura preparada para receber dados posteriormente.</p></div><div className="counter"><strong>--</strong><span>OPÇÕES DISPONÍVEIS<br/><small>aguardando dados</small></span></div><div className="accountGrid"><Card img={I.card1} id="DUSK-001" onSelect={start}/><Card img={I.card2} id="DUSK-002" onSelect={start}/><Card img={I.card3} id="DUSK-003" onSelect={start}/></div></section>}
function Donation(){return <section className="donation"><div className="donationImage"><img src={I.card3} alt="Arte gamer"/></div><div><span className="eyebrow">PROCESSO TRANSPARENTE</span><h2>OPORTUNIDADES GAMER</h2><p>Processo transparente e informações claras sobre cada oportunidade disponível.</p><div className="checks"><span>✓ Informações claras</span><span>✓ Experiência responsiva</span><span>✓ Conteúdo editável</span></div></div></section>}
function Gallery(){return <section className="gallery"><div className="sectionTitle"><span className="eyebrow">COLEÇÃO VISUAL</span><h2>Conteúdo em destaque</h2></div><div className="galleryGrid">{[I.card1,I.card2,I.card3].map((x,i)=><div className="galleryCard" key={x}><img src={x} alt={"Conteúdo DUSK "+(i+1)}/></div>)}</div></section>}
function Tutorial({go}){return <section className="tutorial"><div className="sectionTitle"><span className="eyebrow">COMO FUNCIONA</span><h2>Siga as etapas</h2></div><img src={I.card3} alt="Guia visual"/><button className="primary" onClick={go}>CONTINUAR →</button></section>}
function Loading({active=false}){return <div className="stage"><div className="spinner"/><span className="eyebrow">DUSK FF MAX</span><h2>{active?"ATIVANDO ACESSO":"PREPARANDO ACESSO..."}</h2><p>{active?"Etapa demonstrativa concluída. Nenhuma ação externa é realizada.":"Processando a próxima etapa da experiência."}</p></div>}
function Options({select}){return <section className="options"><div className="sectionTitle"><span className="eyebrow">PRÓXIMA ETAPA</span><h2>ESCOLHA UMA OPÇÃO</h2></div><div className="optionGrid"><button onClick={()=>select(1)}><strong>OPÇÃO 1</strong><span>Configuração interna</span>→</button><button onClick={()=>select(2)}><strong>OPÇÃO 2</strong><span>Configuração interna</span>→</button></div></section>}
function Steps({option,finish}){return <section className="steps"><div className="sectionTitle"><span className="eyebrow">PASSO A PASSO</span><h2>Continue pelas etapas abaixo.</h2></div><img className="tutorialImg" src={I.card3} alt="Guia visual"/><div className="numbered">{["Primeira etapa","Segunda etapa","Terceira etapa","Última etapa"].map((x,i)=><div key={x}><b>{i+1}.</b><span>{x}</span></div>)}</div><button className="primary final" onClick={finish}>CONCLUIR ETAPA {option}</button></section>}
function App(){const[s,setS]=useState("home"),[o,setO]=useState(null);const start=()=>{setS("loading");setTimeout(()=>setS("activation"),1200);setTimeout(()=>setS("account"),2400)};const select=x=>{setO(x);setS("steps")};return <><Header/><main>{s==="home"&&<><Hero start={start}/><Activity/><Accounts start={start}/><Donation/><Gallery/><Tutorial go={()=>setS("options")}/></>}{s==="loading"&&<Loading/>}{s==="activation"&&<Loading active/>}{s==="account"&&<section className="release"><span className="eyebrow">ETAPA CONCLUÍDA</span><h2>Acesso preparado</h2><p>A apresentação abaixo é demonstrativa.</p><Card img={I.card1} id="DUSK-001" onSelect={()=>setS("tutorial")}/><button className="primary" onClick={()=>setS("tutorial")}>COMO FUNCIONA →</button></section>}{s==="tutorial"&&<Tutorial go={()=>setS("options")}/>} {s==="options"&&<Options select={select}/>} {s==="steps"&&<Steps option={o} finish={()=>setS("done")}/>} {s==="done"&&<section className="release"><span className="eyebrow">PROCESSO CONCLUÍDO</span><h2>Acesso ativado</h2><p>Esta etapa é apenas uma demonstração interna da interface.</p><button className="primary" onClick={()=>setS("home")}>VOLTAR AO INÍCIO</button></section>}</main><footer>DUSK FF MAX <span>Experiência independente · conteúdo editável</span></footer></>}
createRoot(document.getElementById("root")).render(<App/>);